spring:
  application:
    name: nexuspay
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_pay
    username: postgres 
    password: postgres
  jpa:
    show-sql: false
    format_sql: false
    properties:
      jakarta:
        persistence: 
          schema-generation:
            scripts:
              action: create 
              create-target: script.sql 
      hibernate:
        ddl-auto: validate
        hbm2ddl:
          delimiter:;
  web:
    error:
      include-stacktrace: never
