spring:
  flyway:
    enabled: false
  application:
    name: nexuspay
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_pay
    username: postgres 
    password: postgres
  jpa:
    properties:
      jakarta:
        persistence: 
          schema-generation:
            scripts:
              action: create 
              create-target: script.sql 
      hibernate:
        hbm2ddl:
          delimiter:;
